version: '2'

services:
  config-primary:
    image: lgatica/mongodb-sharded-config:latest@sha256:efe9415d04e6c70286cf78a7b0b429c867102f13d7af91afd85f22b43f3645c4
    stdin_open: true
    tty: true
    volumes:
    - /run/secrets
    - /opt/mongodb/scripts
    environment:
      MONGODB_KEYFILE_SECRET: '${MONGODB_KEYFILE_SECRET}'
      MONGODB_PASSWORD_ADMIN_USER_SECRET: '${MONGODB_PASSWORD_ADMIN_USER_SECRET}'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  config-secundary:
    image: lgatica/mongodb-sharded-config:latest@sha256:efe9415d04e6c70286cf78a7b0b429c867102f13d7af91afd85f22b43f3645c4
    stdin_open: true
    tty: true
    volumes:
    - /run/secrets
    - /opt/mongodb/scripts
    environment:
      MONGODB_KEYFILE_SECRET: '${MONGODB_KEYFILE_SECRET}'
      MONGODB_PASSWORD_ADMIN_USER_SECRET: '${MONGODB_PASSWORD_ADMIN_USER_SECRET}'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  config-arbiter:
    image: lgatica/mongodb-sharded-config:latest@sha256:efe9415d04e6c70286cf78a7b0b429c867102f13d7af91afd85f22b43f3645c4
    stdin_open: true
    tty: true
    volumes:
    - /run/secrets
    - /opt/mongodb/scripts
    environment:
      MONGODB_KEYFILE_SECRET: '${MONGODB_KEYFILE_SECRET}'
      MONGODB_PASSWORD_ADMIN_USER_SECRET: '${MONGODB_PASSWORD_ADMIN_USER_SECRET}'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  config-configsvr-1:
    image: lgatica/mongodb-sharded-config:latest@sha256:efe9415d04e6c70286cf78a7b0b429c867102f13d7af91afd85f22b43f3645c4
    stdin_open: true
    tty: true
    volumes:
    - /run/secrets
    - /opt/mongodb/scripts
    environment:
      MONGODB_KEYFILE_SECRET: '${MONGODB_KEYFILE_SECRET}'
      MONGODB_PASSWORD_ADMIN_USER_SECRET: '${MONGODB_PASSWORD_ADMIN_USER_SECRET}'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  config-configsvr-2:
    image: lgatica/mongodb-sharded-config:latest@sha256:efe9415d04e6c70286cf78a7b0b429c867102f13d7af91afd85f22b43f3645c4
    stdin_open: true
    tty: true
    volumes:
    - /run/secrets
    - /opt/mongodb/scripts
    environment:
      MONGODB_KEYFILE_SECRET: '${MONGODB_KEYFILE_SECRET}'
      MONGODB_PASSWORD_ADMIN_USER_SECRET: '${MONGODB_PASSWORD_ADMIN_USER_SECRET}'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  config-configsvr-3:
    image: lgatica/mongodb-sharded-config:latest@sha256:efe9415d04e6c70286cf78a7b0b429c867102f13d7af91afd85f22b43f3645c4
    stdin_open: true
    tty: true
    volumes:
    - /run/secrets
    - /opt/mongodb/scripts
    environment:
      MONGODB_KEYFILE_SECRET: '${MONGODB_KEYFILE_SECRET}'
      MONGODB_PASSWORD_ADMIN_USER_SECRET: '${MONGODB_PASSWORD_ADMIN_USER_SECRET}'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  config-router:
    image: lgatica/mongodb-sharded-config:latest@sha256:efe9415d04e6c70286cf78a7b0b429c867102f13d7af91afd85f22b43f3645c4
    stdin_open: true
    tty: true
    volumes:
    - /run/secrets
    - /opt/mongodb/scripts
    environment:
      MONGODB_KEYFILE_SECRET: '${MONGODB_KEYFILE_SECRET}'
      MONGODB_PASSWORD_ADMIN_USER_SECRET: '${MONGODB_PASSWORD_ADMIN_USER_SECRET}'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  primary:
    image: mongo:3.4.9@sha256:97c51a36d08871557c02e64d20a9a6b645b16ce387b39ae4414609c39dfc439c
    stdin_open: true
    volumes_from:
    - config-primary
    tty: true
    links:
    - router:router
    - secundary:secundary
    - arbiter:arbiter
    - configsvr-1:configsvr-1
    - configsvr-2:configsvr-2
    - configsvr-3:configsvr-3
    depends_on:
    - secundary
    - arbiter
    - configsvr-1
    - configsvr-2
    - configsvr-3
    entrypoint: /opt/mongodb/scripts/mongodb-replicaset.init.sh
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: '${MONGODB_PRIMARY_HOST_LABEL}'
      io.rancher.sidekicks: config-primary
  secundary:
    image: mongo:3.4.9@sha256:97c51a36d08871557c02e64d20a9a6b645b16ce387b39ae4414609c39dfc439c
    stdin_open: true
    volumes_from:
    - config-secundary
    tty: true
    links:
    - router:router
    - primary:primary
    - arbiter:arbiter
    - configsvr-1:configsvr-1
    - configsvr-2:configsvr-2
    - configsvr-3:configsvr-3
    depends_on:
    - arbiter
    command:
    - mongod
    - --keyFile
    - /run/secrets/MONGODB_KEYFILE
    - --replSet
    - rs1
    - --shardsvr
    - --dbpath
    - /data/db
    - --port
    - "27017"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: '${MONGODB_SECUNDARY_HOST_LABEL}'
      io.rancher.sidekicks: config-secundary
  arbiter:
    image: mongo:3.4.9@sha256:97c51a36d08871557c02e64d20a9a6b645b16ce387b39ae4414609c39dfc439c
    stdin_open: true
    volumes_from:
    - config-arbiter
    tty: true
    links:
    - router:router
    - secundary:secundary
    - primary:primary
    - configsvr-1:configsvr-1
    - configsvr-2:configsvr-2
    - configsvr-3:configsvr-3
    command:
    - mongod
    - --keyFile
    - /run/secrets/MONGODB_KEYFILE
    - --replSet
    - rs1
    - --shardsvr
    - --dbpath
    - /data/db
    - --port
    - "27017"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: '${MONGODB_ARBITER_HOST_LABEL}'
      io.rancher.sidekicks: config-arbiter
  configsvr-1:
    image: mongo:3.4.9@sha256:97c51a36d08871557c02e64d20a9a6b645b16ce387b39ae4414609c39dfc439c
    stdin_open: true
    volumes_from:
    - config-configsvr-1
    tty: true
    links:
    - router:router
    - secundary:secundary
    - arbiter:arbiter
    - primary:primary
    - configsvr-2:configsvr-2
    - configsvr-3:configsvr-3
    depends_on:
    - configsvr-2
    - configsvr-3
    entrypoint: /opt/mongodb/scripts/mongodb-configsvr.init.sh
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: '${MONGODB_CONFIG1_HOST_LABEL}'
      io.rancher.sidekicks: config-configsvr-1
  configsvr-2:
    image: mongo:3.4.9@sha256:97c51a36d08871557c02e64d20a9a6b645b16ce387b39ae4414609c39dfc439c
    stdin_open: true
    volumes_from:
    - config-configsvr-2
    tty: true
    links:
    - router:router
    - secundary:secundary
    - arbiter:arbiter
    - configsvr-1:configsvr-1
    - primary:primary
    - configsvr-3:configsvr-3
    depends_on:
    - configsvr-3
    command:
    - mongod
    - --configsvr
    - --dbpath
    - /data/db
    - --port
    - "27017"
    - --keyFile
    - /run/secrets/MONGODB_KEYFILE
    - --replSet
    - mongodb-configserver
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: '${MONGODB_CONFIG2_HOST_LABEL}'
      io.rancher.sidekicks: config-configsvr-2
  configsvr-3:
    image: mongo:3.4.9@sha256:97c51a36d08871557c02e64d20a9a6b645b16ce387b39ae4414609c39dfc439c
    stdin_open: true
    volumes_from:
    - config-configsvr-3
    tty: true
    links:
    - router:router
    - secundary:secundary
    - arbiter:arbiter
    - configsvr-1:configsvr-1
    - primary:primary
    - configsvr-2:configsvr-2
    command:
    - mongod
    - --configsvr
    - --dbpath
    - /data/db
    - --port
    - "27017"
    - --keyFile
    - /run/secrets/MONGODB_KEYFILE
    - --replSet
    - mongodb-configserver
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: '${MONGODB_CONFIG3_HOST_LABEL}'
      io.rancher.sidekicks: config-configsvr-3
  router:
    image: mongo:3.4.9@sha256:97c51a36d08871557c02e64d20a9a6b645b16ce387b39ae4414609c39dfc439c
    stdin_open: true
    volumes_from:
    - config-router
    links:
    - primary:primary
    - secundary:secundary
    - arbiter:arbiter
    - configsvr-1:configsvr-1
    - configsvr-2:configsvr-2
    - configsvr-3:configsvr-3
    depends_on:
    - primary
    - secundary
    - arbiter
    - configsvr-1
    - configsvr-2
    - configsvr-3
    ports:
    - '${MONGODB_PORT}:27017'
    tty: true
    entrypoint: /opt/mongodb/scripts/mongodb-router.init.sh
    environment:
      MONGODB_DBNAME: '${MONGODB_DBNAME}'
      MONGODB_ADMIN_USER: '${MONGODB_ADMIN_USER}'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: '${MONGODB_ROUTER_HOST_LABEL}'
      io.rancher.sidekicks: config-router
