.catalog:
  name: "MongoDB Sharded"
  version: "v1.0.0"
  description: |
    MongoDB Sharded Cluster
  questions:
    - variable: MONGODB_KEYFILE_SECRET
      type: multiline
      required: true
      label: "MongoDB Keyfile"
    - variable: MONGODB_PASSWORD_ADMIN_USER_SECRET
      type: string
      required: true
      label: "Password for admin user"
    - variable: MONGODB_ADMIN_USER
      type: string
      required: false
      default: "admin"
      label: "Username for admin user"
    - variable: MONGODB_DBNAME
      type: string
      required: false
      default: "mydb"
      label: "Database name"
    - variable: MONGODB_PRIMARY_HOST_LABEL
      type: string
      required: true
      default: "mongodb.replicaset.role=primary"
      label: "Host label for primary"
    - variable: MONGODB_SECUNDARY_HOST_LABEL
      type: string
      required: true
      default: "mongodb.replicaset.role=secundary"
      label: "Host label for secundary"
    - variable: MONGODB_ARBITER_HOST_LABEL
      type: string
      required: true
      default: "mongodb.replicaset.role=arbiter"
      label: "Host label for arbiter"
    - variable: MONGODB_ROUTER_HOST_LABEL
      type: string
      required: true
      default: "mongodb.replicaset.role=router"
      label: "Host label for router"
    - variable: MONGODB_CONFIG1_HOST_LABEL
      type: string
      required: true
      default: "mongodb.replicaset.role=secundary"
      label: "Host label for config server 1"
    - variable: MONGODB_CONFIG2_HOST_LABEL
      type: string
      required: true
      default: "mongodb.replicaset.role=arbiter"
      label: "Host label for config server 2"
    - variable: MONGODB_CONFIG3_HOST_LABEL
      type: string
      required: true
      default: "mongodb.replicaset.role=router"
      label: "Host label for config server 3"

version: '2'
services:
  primary:
    scale: 1
    start_on_create: true
  secundary:
    scale: 1
    start_on_create: true
  arbiter:
    scale: 1
    start_on_create: true
  config-1:
    scale: 1
    start_on_create: true
  config-2:
    scale: 1
    start_on_create: true
  config-3:
    scale: 1
    start_on_create: true
  router:
    scale: 1
    start_on_create: true
